//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KBS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 381b4222-f694-41f0-9685-ff5bb260df2e.
        /// </summary>
        public static string BalancedModeGUID {
            get {
                return ResourceManager.GetString("BalancedModeGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбалансированный режим.
        /// </summary>
        public static string BalancedModeTitle {
            get {
                return ResourceManager.GetString("BalancedModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Disable {
            get {
                object obj = ResourceManager.GetObject("Disable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить.
        /// </summary>
        public static string DisableText {
            get {
                return ResourceManager.GetString("DisableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Enable {
            get {
                object obj = ResourceManager.GetObject("Enable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить.
        /// </summary>
        public static string EnableText {
            get {
                return ResourceManager.GetString("EnableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a1841308-3541-4fab-bc81-f71556f20b4a.
        /// </summary>
        public static string EnergySavingGUID {
            get {
                return ResourceManager.GetString("EnergySavingGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экономия заряда.
        /// </summary>
        public static string EnergySavingTitle {
            get {
                return ResourceManager.GetString("EnergySavingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий процесс будет закрыт..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение уже запущено.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to powercfg /getactivescheme.
        /// </summary>
        public static string GetCurrentShemeCmd {
            get {
                return ResourceManager.GetString("GetCurrentShemeCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c.
        /// </summary>
        public static string HighPerformanceGUID {
            get {
                return ResourceManager.GetString("HighPerformanceGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высокая производительность.
        /// </summary>
        public static string HighPerformanceTitle {
            get {
                return ResourceManager.GetString("HighPerformanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEngText {
            get {
                return ResourceManager.GetString("LanguageEngText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string LanguageRusText {
            get {
                return ResourceManager.GetString("LanguageRusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать план.
        /// </summary>
        public static string SubMenuTitle {
            get {
                return ResourceManager.GetString("SubMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krimmel Battery Saver - Выключено.
        /// </summary>
        public static string TipDisableText {
            get {
                return ResourceManager.GetString("TipDisableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krimmel Battery Saver - Включено.
        /// </summary>
        public static string TipEnableText {
            get {
                return ResourceManager.GetString("TipEnableText", resourceCulture);
            }
        }
    }
}
